# Rose Pine Theme for Yazi
# ~/.config/yazi/themes/rose-pine.toml

[theme]
# Base colors
primary = "#e0def4"    # Text
secondary = "#908caa"  # Subtext
inactive = "#6e6a86"   # Muted
background = "#191724" # Base
current = "#1f1d2e"    # Surface 0
hover = "#26233a"      # Surface 1
border = "#31748f"     # Pine

# Status colors
warning = "#f6c177"    # Gold
error = "#eb6f92"      # Love
info = "#9ccfd8"       # Foam
success = "#9ccfd8"    # Foam

# Selection and highlights
selection = "#31748f"  # Pine
highlight = "#c4a7e7"  # Iris

# Syntax highlighting (for preview)
syntax = [
    { fg = "#e0def4" }, # Default text
    { fg = "#eb6f92" }, # Keywords, errors
    { fg = "#9ccfd8" }, # Strings, success
    { fg = "#f6c177" }, # Numbers, constants
    { fg = "#c4a7e7" }, # Functions, types
    { fg = "#ebbcba" }, # Comments
    { fg = "#31748f" }, # Operators
]

[theme.manager]
# File manager colors
cursor = "#31748f"              # Pine - Current selection
preview_border = "#c4a7e7"      # Iris - Preview border
marker = "#eb6f92"              # Love - Selected files
tab_active = "#e0def4"          # Text - Active tab
tab_inactive = "#6e6a86"        # Muted - Inactive tab
header = "#9ccfd8"              # Foam - Header text
linemode = "#908caa"            # Subtext - File details

[theme.status]
# Status bar colors
mode_normal = "#9ccfd8"         # Foam - Normal mode
mode_select = "#f6c177"         # Gold - Select mode
mode_unset = "#eb6f92"          # Love - Unset mode
progress = "#31748f"            # Pine - Progress bar
permissions = "#c4a7e7"         # Iris - Permissions text

[theme.input]
# Input field colors
suggest_selected = "#31748f"    # Pine - Selected suggestion
suggest_border = "#c4a7e7"      # Iris - Suggestion border

[theme.tasks]
# Task manager colors
hover = "#26233a"               # Surface 1 - Hovered task
active = "#31748f"              # Pine - Active task

[theme.which]
# Which key colors
keys = "#f6c177"                # Gold - Key bindings
values = "#9ccfd8"              # Foam - Key descriptions
