"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[󱞪](fg:iris) \
"""

palette = "rose-pine"

[palettes.rose-pine]
bakground-color = '#26233a'
github-status-problem-color = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[directory]
format = "[](fg:bakground-color)[ $path ]($style)[](fg:bakground-color) "
style = "bg:bakground-color fg:pine"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:bakground-color"
symbol = " "

[git_branch]
format = "[](fg:bakground-color)[ $symbol $branch ]($style)[](fg:bakground-color) "
style = "bg:bakground-color fg:foam"
symbol = ""

[git_status]
disabled = false
style = "bg:bakground-color fg:github-status-problem-color"
format = '[](fg:bakground-color)([$all_status$ahead_behind]($style))[](fg:bakground-color) '
up_to_date = '[ ✓ ](bg:bakground-color fg:iris)'
untracked = '[?\($count\)](bg:bakground-color fg:gold)'
stashed = '[\$](bg:bakground-color fg:iris)'
modified = '[!\($count\)](bg:bakground-color fg:gold)'
renamed = '[»\($count\)](bg:bakground-color fg:iris)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:bakground-color fg:gold)'
ahead = '[⇡\(${count}\)](bg:bakground-color fg:foam)'
diverged = '⇕[\[](bg:bakground-color fg:iris)[⇡\(${ahead_count}\)](bg:bakground-color fg:foam)[⇣\(${behind_count}\)](bg:bakground-color fg:rose)[\]](bg:bakground-color fg:iris)'
behind = '[⇣\(${count}\)](bg:bakground-color fg:rose)'

[time]
disabled = false
format = " [](fg:bakground-color)[ $time 󰴈 ]($style)[](fg:bakground-color)"
style = "bg:bakground-color fg:rose"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[](fg:bakground-color)[ 󰧱 $user ]($style)[](fg:bakground-color) "
show_always = true
style_root = "bg:bakground-color fg:iris"
style_user = "bg:bakground-color fg:iris"

[c]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = " "

[elixir]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = " "

[elm]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = " "

[golang]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = " "

[haskell]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = " "

[java]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = " "

[julia]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = " "

[nodejs]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = " "

[scala]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = " "

[python]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$version ]($style)[](fg:bakground-color)"
disabled = false
symbol = ' '

[conda]
style = "bg:bakground-color fg:pine"
format = " [](fg:bakground-color)[ $symbol$environment ]($style)[](fg:bakground-color)"
disabled = false
symbol = '🅒 '
